# Generated by Django 5.1.5 on 2025-03-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
