# Generated by Django 5.1.5 on 2025-03-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_liked_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
